changelog:
  exclude:
    labels:
    - ignore-for-release
    authors:
    - dependabot
  categories:
  - title: 🚀 New Features
    labels:
    - feature
    - enhancement
    commits:
    - feat*
    - feature*
  - title: 🐛 Bug Fixes
    labels:
    - fix
    - bugfix
    commits:
    - fix*
  - title: ⚙️ Improvements
    labels:
    - refactor
    commits:
    - refactor*
    - perf*
  - title: 📚 Documentation
    labels:
    - documentation
    commits:
    - docs*
  - title: 🔧 Other Changes
    labels:
    - '*'
